version: '3'
services:
  app:
    build: .
    volumes:
      - .:/code
    tty: true
    ports:
      - "8000:5000"
  db:
    image: mariadb:latest
    volumes:
      -  ./dbdata:/var/lib/mysql
    ports:
        - "3308:3308"
    expose:
        - "3308"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "hoge"
volumes:
  dbdata: